careshare:
  build: ./careshare/
  ports:
    - "80:4200"

openid:
  env_file: ./common.env
  build: ./vha-rural-health-openid-connect-overlay/
  ports:
    - "8888:8080"

fhir:
  env_file: ./common.env
  build: ./hapi-docker/
  ports:
    - "8080:8080"

