careshare:
  env_file: ./common.env
  build: ./careshare/

careshare-remote:
  env_file: ./common.env
  environment:
    - is_openid=true
  build: ./careshare/

careauth:
  env_file: ./common.env
  build: ./careauth/
  ports:
    - "80:80"
  links:
    - careshare
    - careshare-remote
    - openid
    - fhir
    - mongo

openid:
  env_file: ./common.env
  build: ./vha-rural-health-openid-connect-overlay/

fhir:
  env_file: ./common.env
  build: ./hapi-docker/

mongo:
  image: mongo:3

