careshare:
  env_file: ./common.env
  build: ./careshare/

careshare-remote:
  env_file: ./common.env
  environment:
    - is_openid=true
  build: ./careshare/

careauth:
  env_file: ./common.env
  build: ./careauth/
  ports:
    - "80:80"
    - "443:443"
  links:
    - careshare
    - careshare-remote
    - openid
    - fhir
    - nomination-service
    - transcript-service
    - mongo

openid:
  env_file: ./common.env
  build: ./openid/

fhir:
  env_file: ./common.env
  build: ./fhir/
# PORTS SHOULD BE REMOVED FOR PRODUCTION
  ports:
    - "8080:8080"

nomination-service:
  build: ./nomination-service/
  ports:
    - "7293:7293"
  volumes:
    - ./nomination-service/db:/usr/src/db

transcript-service:
  build: ./transcript-api/
# PORTS SHOULD BE REMOVED FOR PRODUCTION
  ports:
    - "3003:3003"

mongo:
  image: mongo:3

