careshare:
  build: ./careshare/
  ports:
    - "4200:4200"

careauth:
  build: ./careauth/
  ports:
    - "80:80"
  links:
    - mongo

openid:
  env_file: ./common.env
  build: ./vha-rural-health-openid-connect-overlay/
  ports:
    - "8888:8080"

fhir:
  env_file: ./common.env
  build: ./hapi-docker/
  ports:
    - "8080:8080"

mongo:
  image: mongo:3

