db:
  image: postgres:9.4
web:
  build: .
  links:
    - app
    # - medrec
  ports:
    - "80:80"
app:
  build: vha-rural-health-pilot-app/
  links:
    - db
  environment:
    RAILS_ENV: production
openid:
  build: ./vha-rural-health-openid-connect-overlay/
  ports:
    - "8080:8080"
# medrec:
#   build: ./vha-rural-health-pilot-medrec-app/
#   links:
#   - db

