careshare:
  build: ./careshare/
  ports:
    - "80:4200"
openid:
  build: ./vha-rural-health-openid-connect-overlay/
  ports:
    - "8888:8080"
  links:
    - db
fhir:
  build: ./hapi-docker/
db:
  image: postgres:9.4
