careshare:
  env_file: ./common.env
  build: ./careshare/

careshare-remote:
  env_file: ./common.env
  environment:
    - is_openid=true
  build: ./careshare/

careauth:
  env_file: ./common.env
  build: ./careauth/
  ports:
    - "80:80"
    - "443:443"
  links:
    - careshare
    - careshare-remote
    - openid
    - fhir
    - nomination-service
    - mongo

openid:
  env_file: ./common.env
  build: ./openid/

fhir:
  env_file: ./common.env
  build: ./fhir/
  ports:
    - "8080:8080"

nomination-service:
  build: ./nomination-service/

mongo:
  image: mongo:3

